//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.25 at 01:55:39 PM EDT 
//


package com.cvent.rfp;

import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.cvent.rfp.constraints.ValidAgendaItem;
import com.cvent.rfp.serializers.JsonTimeSerializer;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * <p>Java class for AgendaItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AgendaItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="TypeId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SetupId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Setup" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Note" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EndTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RequiredRoomSize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ExpectedNumberOfPeople" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="IsRoomInfoRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsTwentyFourHourHoldRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsLocatedAtPrimaryEventVenue" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DayNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsTypeIdValid" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsSetupIdValid" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Days" type="{http://www.example.org/test}Days" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AgendaItem", propOrder = {
    "id",
    "name",
    "number",
    "typeId",
    "type",
    "setupId",
    "setup",
    "note",
    "startTime",
    "endTime",
    "requiredRoomSize",
    "expectedNumberOfPeople",
    "isRoomInfoRequired",
    "isTwentyFourHourHoldRequired",
    "isLocatedAtPrimaryEventVenue",
    "dayNumber",
    "isTypeIdValid",
    "isSetupIdValid",
    "days"
})
@ValidAgendaItem(payload = {

}, groups = {

})
public class AgendaItem {

    @XmlElement(name = "Id", required = true)
    @JsonProperty("")
    protected String id;
    @XmlElement(name = "Name", required = true)
    @NotNull(payload = {

    }, groups = {

    })
    @JsonProperty("")
    @Size(payload = {

    }, groups = {

    })
    protected String name;
    @XmlElement(name = "Number")
    @JsonProperty("")
    @Min(value = 0, payload = {

    }, groups = {

    })
    protected Integer number;
    @XmlElement(name = "TypeId")
    @Min(value = 0, payload = {

    }, groups = {

    })
    @JsonProperty("")
    @NotNull(payload = {

    }, groups = {

    })
    protected Integer typeId;
    @XmlElement(name = "Type", required = true)
    @JsonProperty("")
    protected String type;
    @XmlElement(name = "SetupId")
    @JsonProperty("")
    @Min(value = 0, payload = {

    }, groups = {

    })
    @NotNull(payload = {

    }, groups = {

    })
    protected Integer setupId;
    @XmlElement(name = "Setup", required = true)
    @JsonProperty("")
    protected String setup;
    @XmlElement(name = "Note", required = true)
    @JsonProperty("")
    @NotNull(payload = {

    }, groups = {

    })
    @Size(payload = {

    }, groups = {

    })
    protected String note;
    @XmlElement(name = "StartTime", required = true)
    @JsonProperty("")
    @NotNull(payload = {

    }, groups = {

    })
    @JsonSerialize(using = JsonTimeSerializer.class)
    protected String startTime;
    @XmlElement(name = "EndTime", required = true)
    @JsonProperty("")
    @NotNull(payload = {

    }, groups = {

    })
    @JsonSerialize(using = JsonTimeSerializer.class)
    protected String endTime;
    @XmlElement(name = "RequiredRoomSize")
    @JsonProperty("")
    @NotNull(payload = {

    }, groups = {

    })
    @Min(value = 1, payload = {

    }, groups = {

    })
    protected Integer requiredRoomSize;
    @XmlElement(name = "ExpectedNumberOfPeople")
    @JsonProperty("")
    @NotNull(payload = {

    }, groups = {

    })
    @Min(value = 1, payload = {

    }, groups = {

    })
    protected Integer expectedNumberOfPeople;
    @XmlElement(name = "IsRoomInfoRequired")
    @JsonProperty("")
    @NotNull(payload = {

    }, groups = {

    })
    protected Boolean isRoomInfoRequired;
    @XmlElement(name = "IsTwentyFourHourHoldRequired")
    @JsonProperty("")
    @NotNull(payload = {

    }, groups = {

    })
    protected Boolean isTwentyFourHourHoldRequired;
    @XmlElement(name = "IsLocatedAtPrimaryEventVenue")
    @JsonProperty("")
    @NotNull(payload = {

    }, groups = {

    })
    protected Boolean isLocatedAtPrimaryEventVenue;
    @XmlElement(name = "DayNumber", required = true)
    protected String dayNumber;
    @XmlElement(name = "IsTypeIdValid")
    @JsonIgnore(true)
    protected Boolean isTypeIdValid;
    @XmlElement(name = "IsSetupIdValid")
    @JsonIgnore(true)
    protected Boolean isSetupIdValid;
    @XmlElement(name = "Days")
    protected List<Days> days;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumber(Integer value) {
        this.number = value;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTypeId(Integer value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the setupId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSetupId() {
        return setupId;
    }

    /**
     * Sets the value of the setupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSetupId(Integer value) {
        this.setupId = value;
    }

    /**
     * Gets the value of the setup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSetup() {
        return setup;
    }

    /**
     * Sets the value of the setup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSetup(String value) {
        this.setup = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndTime(String value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the requiredRoomSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRequiredRoomSize() {
        return requiredRoomSize;
    }

    /**
     * Sets the value of the requiredRoomSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRequiredRoomSize(Integer value) {
        this.requiredRoomSize = value;
    }

    /**
     * Gets the value of the expectedNumberOfPeople property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExpectedNumberOfPeople() {
        return expectedNumberOfPeople;
    }

    /**
     * Sets the value of the expectedNumberOfPeople property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExpectedNumberOfPeople(Integer value) {
        this.expectedNumberOfPeople = value;
    }

    /**
     * Gets the value of the isRoomInfoRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsRoomInfoRequired() {
        return isRoomInfoRequired;
    }

    /**
     * Sets the value of the isRoomInfoRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRoomInfoRequired(Boolean value) {
        this.isRoomInfoRequired = value;
    }

    /**
     * Gets the value of the isTwentyFourHourHoldRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsTwentyFourHourHoldRequired() {
        return isTwentyFourHourHoldRequired;
    }

    /**
     * Sets the value of the isTwentyFourHourHoldRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsTwentyFourHourHoldRequired(Boolean value) {
        this.isTwentyFourHourHoldRequired = value;
    }

    /**
     * Gets the value of the isLocatedAtPrimaryEventVenue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsLocatedAtPrimaryEventVenue() {
        return isLocatedAtPrimaryEventVenue;
    }

    /**
     * Sets the value of the isLocatedAtPrimaryEventVenue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsLocatedAtPrimaryEventVenue(Boolean value) {
        this.isLocatedAtPrimaryEventVenue = value;
    }

    /**
     * Gets the value of the dayNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayNumber() {
        return dayNumber;
    }

    /**
     * Sets the value of the dayNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayNumber(String value) {
        this.dayNumber = value;
    }

    /**
     * Gets the value of the isTypeIdValid property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsTypeIdValid() {
        return isTypeIdValid;
    }

    /**
     * Sets the value of the isTypeIdValid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsTypeIdValid(Boolean value) {
        this.isTypeIdValid = value;
    }

    /**
     * Gets the value of the isSetupIdValid property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSetupIdValid() {
        return isSetupIdValid;
    }

    /**
     * Sets the value of the isSetupIdValid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSetupIdValid(Boolean value) {
        this.isSetupIdValid = value;
    }

    /**
     * Gets the value of the days property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the days property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDays().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Days }
     * 
     * 
     */
    public List<Days> getDays() {
        if (days == null) {
            days = new ArrayList<Days>();
        }
        return this.days;
    }

}
