//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.21 at 05:32:51 PM EDT 
//


package com.cvent.rfp;

import com.cvent.rfp.util.DateFormatHelper;
import com.cvent.rfp.util.StringHelper;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.yammer.dropwizard.validation.ValidationMethod;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AgendaItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AgendaItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TypeId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SetupId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Setup" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Note" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StartTimeString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EndTimeString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RequiredRoomSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ExpectedNumberOfPeople" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="IsRoomInfoRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="IsTwentyFourHourHoldRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="IsLocatedAtPrimaryEventVenue" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="dayNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Days" type="{http://www.example.org/test}Days" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AgendaItem", propOrder = {
    "id",
    "name",
    "number",
    "typeId",
    "type",
    "setupId",
    "setup",
    "note",
    "startTimeString",
    "endTimeString",
    "requiredRoomSize",
    "expectedNumberOfPeople",
    "isRoomInfoRequired",
    "isTwentyFourHourHoldRequired",
    "isLocatedAtPrimaryEventVenue",
    "dayNumber",
    "days"
})
public class AgendaItem {

    @XmlElement(name = "Id", required = true)
    @JsonProperty("")
    protected String id;
    @XmlElement(name = "Name", required = true)
    @JsonProperty("")
    @Size(payload = {

    }, groups = {

    })
    protected String name;
    @XmlElement(name = "Number")
    @JsonProperty("")
    @Min(value = 0, payload = {

    }, groups = {

    })
    protected int number;
    @XmlElement(name = "TypeId")
    @Min(value = 0, payload = {

    }, groups = {

    })
    @JsonIgnore(true)
    protected int typeId;
    @XmlElement(name = "Type", required = true)
    @JsonProperty("")
    protected String type;
    @XmlElement(name = "SetupId")
    @Min(value = 0, payload = {

    }, groups = {

    })
    @JsonIgnore(true)
    protected int setupId;
    @XmlElement(name = "Setup", required = true)
    @JsonProperty("")
    protected String setup;
    @XmlElement(name = "Note", required = true)
    @JsonProperty("")
    @Size(payload = {

    }, groups = {

    })
    protected String note;
    @XmlElement(name = "StartTimeString", required = true)
    @JsonProperty("")
    @JsonSerialize(using = com.cvent.rfp.serializers.Time.JsonTimeSerializer.class)
    protected String startTimeString;
    @XmlElement(name = "EndTimeString", required = true)
    @JsonProperty("")
    @JsonSerialize(using = com.cvent.rfp.serializers.Time.JsonTimeSerializer.class)
    protected String endTimeString;
    @XmlElement(name = "RequiredRoomSize")
    @JsonProperty("")
    @Min(value = 1, payload = {

    }, groups = {

    })
    protected int requiredRoomSize;
    @XmlElement(name = "ExpectedNumberOfPeople")
    @JsonProperty("")
    @Min(value = 1, payload = {

    }, groups = {

    })
    protected int expectedNumberOfPeople;
    @XmlElement(name = "IsRoomInfoRequired")
    @JsonProperty("")
    protected boolean isRoomInfoRequired;
    @XmlElement(name = "IsTwentyFourHourHoldRequired")
    @JsonProperty("")
    protected boolean isTwentyFourHourHoldRequired;
    @XmlElement(name = "IsLocatedAtPrimaryEventVenue")
    @JsonProperty("")
    protected boolean isLocatedAtPrimaryEventVenue;
    @XmlElement(required = true)
    @JsonIgnore(true)
    protected String dayNumber;
    @XmlElement(name = "Days")
    protected List<Days> days;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the number property.
     * 
     */
    public int getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     */
    public void setNumber(int value) {
        this.number = value;
    }

    /**
     * Gets the value of the typeId property.
     * 
     */
    public int getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     */
    public void setTypeId(int value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the setupId property.
     * 
     */
    public int getSetupId() {
        return setupId;
    }

    /**
     * Sets the value of the setupId property.
     * 
     */
    public void setSetupId(int value) {
        this.setupId = value;
    }

    /**
     * Gets the value of the setup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSetup() {
        return setup;
    }

    /**
     * Sets the value of the setup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSetup(String value) {
        this.setup = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the startTimeString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTimeString() {
        return startTimeString;
    }

    /**
     * Sets the value of the startTimeString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTimeString(String value) {
        this.startTimeString = value;
    }

    /**
     * Gets the value of the endTimeString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndTimeString() {
        return endTimeString;
    }

    /**
     * Sets the value of the endTimeString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndTimeString(String value) {
        this.endTimeString = value;
    }

    /**
     * Gets the value of the requiredRoomSize property.
     * 
     */
    public int getRequiredRoomSize() {
        return requiredRoomSize;
    }

    /**
     * Sets the value of the requiredRoomSize property.
     * 
     */
    public void setRequiredRoomSize(int value) {
        this.requiredRoomSize = value;
    }

    /**
     * Gets the value of the expectedNumberOfPeople property.
     * 
     */
    public int getExpectedNumberOfPeople() {
        return expectedNumberOfPeople;
    }

    /**
     * Sets the value of the expectedNumberOfPeople property.
     * 
     */
    public void setExpectedNumberOfPeople(int value) {
        this.expectedNumberOfPeople = value;
    }

    /**
     * Gets the value of the isRoomInfoRequired property.
     * 
     */
    public boolean isIsRoomInfoRequired() {
        return isRoomInfoRequired;
    }

    /**
     * Sets the value of the isRoomInfoRequired property.
     * 
     */
    public void setIsRoomInfoRequired(boolean value) {
        this.isRoomInfoRequired = value;
    }

    /**
     * Gets the value of the isTwentyFourHourHoldRequired property.
     * 
     */
    public boolean isIsTwentyFourHourHoldRequired() {
        return isTwentyFourHourHoldRequired;
    }

    /**
     * Sets the value of the isTwentyFourHourHoldRequired property.
     * 
     */
    public void setIsTwentyFourHourHoldRequired(boolean value) {
        this.isTwentyFourHourHoldRequired = value;
    }

    /**
     * Gets the value of the isLocatedAtPrimaryEventVenue property.
     * 
     */
    public boolean isIsLocatedAtPrimaryEventVenue() {
        return isLocatedAtPrimaryEventVenue;
    }

    /**
     * Sets the value of the isLocatedAtPrimaryEventVenue property.
     * 
     */
    public void setIsLocatedAtPrimaryEventVenue(boolean value) {
        this.isLocatedAtPrimaryEventVenue = value;
    }

    /**
     * Gets the value of the dayNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayNumber() {
        return dayNumber;
    }

    /**
     * Sets the value of the dayNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayNumber(String value) {
        this.dayNumber = value;
    }

    /**
     * Gets the value of the days property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the days property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDays().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Days }
     * 
     * 
     */
    public List<Days> getDays() {
        if (days == null) {
            days = new ArrayList<Days>();
        }
        return this.days;
    }

    @JsonIgnore
    @ValidationMethod(message = "startTime/endTime is not in correct time format.")
    public boolean isTimeFormatCorrect()
    {
        try{
            Date startDate = DateFormatHelper.parseDate(startTimeString);
            Date endDate = DateFormatHelper.parseDate(endTimeString);
            
            return true;
        } catch (ParseException ex)
        {
          return false;
        }
    }
    
    @JsonIgnore
    @ValidationMethod(message = "startTime/endTime should be in 15 minutes increments")
    public boolean isTimeFormatInCorrectIncrement()
    {
        List<Integer> minuteList = new ArrayList<>(Arrays.asList(0,15,30,45));
        
        try {
            Date startDate = DateFormatHelper.parseDate(startTimeString);
            Date endDate = DateFormatHelper.parseDate(endTimeString);
            
            return (minuteList.contains(startDate.getMinutes()) && minuteList.contains(endDate.getMinutes()));
        } catch (ParseException ex) {
            return false;
        }
    }
    
    @JsonIgnore
    @ValidationMethod(message = "startTime should be earlier than endTime")
    public boolean isStartTimeBeforeEndTime()
    {
        List<Integer> minuteList = new ArrayList<>(Arrays.asList(0,15,30,45));
        try {
            Date startDate = DateFormatHelper.parseDate(startTimeString);
            Date endDate = DateFormatHelper.parseDate(endTimeString);

            return (startDate.compareTo(endDate) < 0);
        } catch (ParseException ex) {
            return false;
        }
    }
    
    @JsonIgnore
    @ValidationMethod(message = "Either 'Name' or 'Type' is required to create an agenda item.")
    public boolean isNameOrTypePresent()
    {
        return !(StringHelper.isNullOrEmpty(name) && typeId == 0);
    }
    
    @JsonIgnore
    @ValidationMethod(message = "dayNumber input is invalid")
    public boolean isDayNumberValid()
    {
        try {
            List<String> list = Arrays.asList(dayNumber.split(","));
            for (String str : list) Integer.parseInt(str.trim());
            
            return true;
        } catch(NumberFormatException ex) {
            return false;
        }        
    }    
}
