//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.23 at 09:54:14 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/test", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cvent.rfp;
