//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 04:43:41 PM EDT 
//


package com.cvent.rfp.adapter;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class DateAdapter
    extends XmlAdapter<String, Date>
{
    //SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ");

    @Override
    public Date unmarshal(String value) throws Exception {
        //return dateFormat.parse(value);
        return new Date(value);
    }

    @Override
    public String marshal(Date value) {
        if (value == null) {
            return null;
        }
        return value.toString();
    }

}
